version: "3.7"
services:
  qr_server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: qr_server
    ports:
      - "3000:8088"
    logging:
      driver: "json-file"
      options:
        max-size: "250m"
        max-file: "2"
    restart: unless-stopped